-- Fuehre diese Datei einmal komplett im Supabase SQL Editor aus.
-- Die Tabellen speichern nur zusammengefasste Website-Kennzahlen.

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce((auth.jwt() ->> 'email') = 'bastianhochreither@gmx.at', false);
$$;

create table if not exists public.daily_analytics (
  id bigint generated by default as identity primary key,
  date date not null unique,
  visitors integer not null default 0 check (visitors >= 0),
  page_views integer not null default 0 check (page_views >= 0),
  contact_requests integer not null default 0 check (contact_requests >= 0),
  configurations_started integer not null default 0 check (configurations_started >= 0),
  configurations_submitted integer not null default 0 check (configurations_submitted >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_analytics (
  id bigint generated by default as identity primary key,
  date date not null,
  page_path text not null,
  view_count integer not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists page_analytics_date_page_path_idx
on public.page_analytics (date, page_path);

create table if not exists public.model_analytics (
  id bigint generated by default as identity primary key,
  date date not null,
  model_id text not null,
  model_name text not null default '',
  view_count integer not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists model_analytics_date_model_id_idx
on public.model_analytics (date, model_id);

create table if not exists public.visitor_analytics (
  id bigint generated by default as identity primary key,
  date date not null,
  language text not null default 'de',
  device_type text not null default 'desktop',
  source text not null default 'unknown',
  "count" integer not null default 0 check ("count" >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint visitor_analytics_language_check check (language in ('de', 'en', 'sk')),
  constraint visitor_analytics_device_type_check check (device_type in ('desktop', 'tablet', 'mobile')),
  constraint visitor_analytics_source_check check (source in ('google', 'direct', 'external', 'unknown'))
);

create unique index if not exists visitor_analytics_daily_dimension_idx
on public.visitor_analytics (date, language, device_type, source);

alter table public.daily_analytics enable row level security;
alter table public.page_analytics enable row level security;
alter table public.model_analytics enable row level security;
alter table public.visitor_analytics enable row level security;

revoke all on table public.daily_analytics from anon, authenticated;
revoke all on table public.page_analytics from anon, authenticated;
revoke all on table public.model_analytics from anon, authenticated;
revoke all on table public.visitor_analytics from anon, authenticated;

grant select on table public.daily_analytics to authenticated;
grant select on table public.page_analytics to authenticated;
grant select on table public.model_analytics to authenticated;
grant select on table public.visitor_analytics to authenticated;

drop policy if exists "analytics admin read daily" on public.daily_analytics;
create policy "analytics admin read daily"
on public.daily_analytics
for select
to authenticated
using (public.is_admin());

drop policy if exists "analytics admin read pages" on public.page_analytics;
create policy "analytics admin read pages"
on public.page_analytics
for select
to authenticated
using (public.is_admin());

drop policy if exists "analytics admin read models" on public.model_analytics;
create policy "analytics admin read models"
on public.model_analytics
for select
to authenticated
using (public.is_admin());

drop policy if exists "analytics admin read visitors" on public.visitor_analytics;
create policy "analytics admin read visitors"
on public.visitor_analytics
for select
to authenticated
using (public.is_admin());

create or replace function public.track_analytics_event(
  p_event_type text,
  p_event_date date default current_date,
  p_page_path text default null,
  p_model_id text default null,
  p_model_name text default null,
  p_language text default 'de',
  p_device_type text default 'desktop',
  p_source text default 'unknown',
  p_count_visitor boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_type text := lower(trim(coalesce(p_event_type, '')));
  v_date date := coalesce(p_event_date, current_date);
  v_page_path text := nullif(left(trim(coalesce(p_page_path, '')), 120), '');
  v_model_id text := nullif(left(trim(coalesce(p_model_id, '')), 120), '');
  v_model_name text := left(trim(coalesce(p_model_name, '')), 160);
  v_language text := case when p_language in ('de', 'en', 'sk') then p_language else 'de' end;
  v_device_type text := case when p_device_type in ('desktop', 'tablet', 'mobile') then p_device_type else 'desktop' end;
  v_source text := case when p_source in ('google', 'direct', 'external', 'unknown') then p_source else 'unknown' end;
begin
  if v_event_type not in (
    'page_view',
    'model_view',
    'contact_request',
    'configuration_started',
    'configuration_submitted'
  ) then
    return;
  end if;

  insert into public.daily_analytics (
    date,
    visitors,
    page_views,
    contact_requests,
    configurations_started,
    configurations_submitted
  )
  values (
    v_date,
    case when v_event_type = 'page_view' and p_count_visitor then 1 else 0 end,
    case when v_event_type = 'page_view' then 1 else 0 end,
    case when v_event_type = 'contact_request' then 1 else 0 end,
    case when v_event_type = 'configuration_started' then 1 else 0 end,
    case when v_event_type = 'configuration_submitted' then 1 else 0 end
  )
  on conflict (date) do update set
    visitors = public.daily_analytics.visitors + excluded.visitors,
    page_views = public.daily_analytics.page_views + excluded.page_views,
    contact_requests = public.daily_analytics.contact_requests + excluded.contact_requests,
    configurations_started = public.daily_analytics.configurations_started + excluded.configurations_started,
    configurations_submitted = public.daily_analytics.configurations_submitted + excluded.configurations_submitted,
    updated_at = now();

  if v_event_type = 'page_view' and v_page_path is not null then
    insert into public.page_analytics (date, page_path, view_count)
    values (v_date, v_page_path, 1)
    on conflict (date, page_path) do update set
      view_count = public.page_analytics.view_count + 1,
      updated_at = now();
  end if;

  if v_event_type = 'page_view' and p_count_visitor then
    insert into public.visitor_analytics (date, language, device_type, source, "count")
    values (v_date, v_language, v_device_type, v_source, 1)
    on conflict (date, language, device_type, source) do update set
      "count" = public.visitor_analytics."count" + 1,
      updated_at = now();
  end if;

  if v_event_type = 'model_view' and v_model_id is not null then
    insert into public.model_analytics (date, model_id, model_name, view_count)
    values (v_date, v_model_id, v_model_name, 1)
    on conflict (date, model_id) do update set
      model_name = excluded.model_name,
      view_count = public.model_analytics.view_count + 1,
      updated_at = now();
  end if;
end;
$$;

revoke all on function public.track_analytics_event(
  text,
  date,
  text,
  text,
  text,
  text,
  text,
  text,
  boolean
) from public;

grant execute on function public.track_analytics_event(
  text,
  date,
  text,
  text,
  text,
  text,
  text,
  text,
  boolean
) to anon, authenticated;
