-- Fuehre diese Datei komplett im Supabase SQL Editor aus.
-- Sie erweitert den bestehenden Adminbereich "Eingaenge" um Kontaktanfragen.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;
grant select on table public.admin_users to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
      and active = true
      and role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "admin users admin read" on public.admin_users;
create policy "admin users admin read"
on public.admin_users
for select
to authenticated
using (public.is_admin());

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null default '',
  subject text not null,
  message text not null,
  source text not null default 'contact',
  status text not null default 'new',
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contact_requests add column if not exists customer_name text not null default '';
alter table public.contact_requests add column if not exists customer_email text not null default '';
alter table public.contact_requests add column if not exists customer_phone text not null default '';
alter table public.contact_requests add column if not exists subject text not null default '';
alter table public.contact_requests add column if not exists message text not null default '';
alter table public.contact_requests add column if not exists source text not null default 'contact';
alter table public.contact_requests add column if not exists status text not null default 'new';
alter table public.contact_requests add column if not exists is_read boolean not null default false;
alter table public.contact_requests add column if not exists created_at timestamptz not null default now();
alter table public.contact_requests add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'contact_requests_status_check') then
    alter table public.contact_requests
      add constraint contact_requests_status_check
      check (status in ('new', 'open', 'answered'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_source_check') then
    alter table public.contact_requests
      add constraint contact_requests_source_check
      check (source in ('contact', 'configurator'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_customer_name_length_check') then
    alter table public.contact_requests
      add constraint contact_requests_customer_name_length_check
      check (length(trim(customer_name)) between 2 and 120);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_customer_email_check') then
    alter table public.contact_requests
      add constraint contact_requests_customer_email_check
      check (
        length(trim(customer_email)) between 6 and 160
        and customer_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
      );
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_customer_phone_check') then
    alter table public.contact_requests
      add constraint contact_requests_customer_phone_check
      check (
        customer_phone = ''
        or (
          length(customer_phone) <= 60
          and length(regexp_replace(customer_phone, '\D', '', 'g')) >= 5
          and customer_phone ~ '^[+0-9 ()\-/\.]{5,60}$'
        )
      );
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_subject_length_check') then
    alter table public.contact_requests
      add constraint contact_requests_subject_length_check
      check (length(trim(subject)) between 3 and 160);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'contact_requests_message_length_check') then
    alter table public.contact_requests
      add constraint contact_requests_message_length_check
      check (length(trim(message)) between 10 and 3000);
  end if;
end $$;

create index if not exists contact_requests_created_at_idx
on public.contact_requests (created_at desc);

create index if not exists contact_requests_status_read_idx
on public.contact_requests (status, is_read, created_at desc);

create or replace function public.set_contact_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_contact_requests_updated_at on public.contact_requests;
create trigger set_contact_requests_updated_at
before update on public.contact_requests
for each row
execute function public.set_contact_requests_updated_at();

alter table public.contact_requests enable row level security;

revoke all on table public.contact_requests from anon, authenticated;
grant insert (
  customer_name,
  customer_email,
  customer_phone,
  subject,
  message,
  source
) on table public.contact_requests to anon, authenticated;
grant select on table public.contact_requests to authenticated;
grant update (status, is_read) on table public.contact_requests to authenticated;

revoke usage, select on all sequences in schema public from anon, authenticated;
do $$
declare
  v_contact_sequence regclass;
  v_reference_sequence regclass;
begin
  select pg_get_serial_sequence('public.contact_requests', 'id')::regclass
  into v_contact_sequence;

  if v_contact_sequence is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', v_contact_sequence);
  end if;

  if to_regclass('public.customer_references') is not null then
    select pg_get_serial_sequence('public.customer_references', 'id')::regclass
    into v_reference_sequence;

    if v_reference_sequence is not null then
      execute format('grant usage, select on sequence %s to anon, authenticated', v_reference_sequence);
    end if;
  end if;
end $$;

drop policy if exists "contact requests public insert" on public.contact_requests;
create policy "contact requests public insert"
on public.contact_requests
for insert
to anon, authenticated
with check (status = 'new' and is_read = false);

drop policy if exists "contact requests admin read" on public.contact_requests;
create policy "contact requests admin read"
on public.contact_requests
for select
to authenticated
using (public.is_admin());

drop policy if exists "contact requests admin update" on public.contact_requests;
create policy "contact requests admin update"
on public.contact_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Kontaktanfragen werden nicht automatisch geloescht.
-- Statuswerte:
-- new      = neu oder ungelesen
-- open     = fuer spaeter aufgehoben
-- answered = ueber E-Mail beantwortet
