-- Fuehre diese Datei komplett im Supabase SQL Editor aus.
-- Sie ergaenzt den Adminbereich um Kundenverwaltung und sichere Bewertungs-Follow-ups.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  email_normalized text generated always as (lower(btrim(email))) stored,
  purchase_date date not null,
  purchased_item text not null,
  notes text not null default '',
  preferred_language text not null default 'de',
  review_status text not null default 'none',
  review_found_at timestamptz,
  review_source text,
  matched_reference_id bigint,
  manual_review_confirmed_at timestamptz,
  manual_review_source text,
  follow_up_enabled boolean not null default true,
  follow_up_permission_status text not null default 'unknown',
  follow_up_permission_captured_at timestamptz,
  follow_up_permission_source text not null default '',
  follow_up_permission_text_version text not null default '',
  follow_up_permission_information text not null default '',
  follow_up_opt_out boolean not null default false,
  follow_up_opted_out_at timestamptz,
  two_month_email_status text not null default 'pending',
  two_month_email_sent_at timestamptz,
  two_month_email_attempted_at timestamptz,
  two_month_email_attempts integer not null default 0,
  six_month_email_status text not null default 'pending',
  six_month_email_sent_at timestamptz,
  six_month_email_attempted_at timestamptz,
  six_month_email_attempts integer not null default 0,
  twelve_month_email_status text not null default 'pending',
  twelve_month_email_sent_at timestamptz,
  twelve_month_email_attempted_at timestamptz,
  twelve_month_email_attempts integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint customers_name_length_check check (length(btrim(name)) between 2 and 160),
  constraint customers_email_check check (
    length(btrim(email)) between 6 and 160
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
  ),
  constraint customers_purchase_date_check check (
    purchase_date >= date '2000-01-01'
    and purchase_date <= ((now() at time zone 'Europe/Vienna')::date + interval '1 day')::date
  ),
  constraint customers_purchased_item_length_check check (length(btrim(purchased_item)) between 2 and 180),
  constraint customers_notes_length_check check (length(notes) <= 3000),
  constraint customers_preferred_language_check check (preferred_language in ('de', 'en', 'sk')),
  constraint customers_review_status_check check (review_status in ('none', 'auto_matched', 'manual_confirmed')),
  constraint customers_review_source_check check (
    review_source is null
    or review_source in ('asea_website', 'google', 'personal', 'phone', 'other')
  ),
  constraint customers_manual_review_source_check check (
    manual_review_source is null
    or manual_review_source in ('asea_website', 'google', 'personal', 'phone', 'other')
  ),
  constraint customers_permission_status_check check (
    follow_up_permission_status in ('unknown', 'consented', 'existing_customer_permitted', 'revoked', 'blocked')
  ),
  constraint customers_mail_status_check check (
    two_month_email_status in ('pending', 'processing', 'sent', 'failed', 'skipped')
    and six_month_email_status in ('pending', 'processing', 'sent', 'failed', 'skipped')
    and twelve_month_email_status in ('pending', 'processing', 'sent', 'failed', 'skipped')
  ),
  constraint customers_attempts_check check (
    two_month_email_attempts between 0 and 3
    and six_month_email_attempts between 0 and 3
    and twelve_month_email_attempts between 0 and 3
  )
);

create unique index if not exists customers_email_normalized_active_idx
on public.customers (email_normalized)
where deleted_at is null;

create index if not exists customers_purchase_date_idx
on public.customers (purchase_date);

create index if not exists customers_review_status_idx
on public.customers (review_status);

create index if not exists customers_followup_status_idx
on public.customers (
  follow_up_enabled,
  follow_up_opt_out,
  follow_up_permission_status,
  purchase_date
)
where deleted_at is null;

create table if not exists public.customer_followup_events (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  event_type text not null,
  reminder_stage text,
  status text,
  error_code text,
  actor_user_id uuid,
  created_at timestamptz not null default now(),
  constraint customer_followup_events_type_length_check check (length(btrim(event_type)) between 2 and 80),
  constraint customer_followup_events_stage_check check (
    reminder_stage is null
    or reminder_stage in ('two_month', 'six_month', 'twelve_month')
  ),
  constraint customer_followup_events_status_check check (
    status is null
    or status in ('pending', 'processing', 'sent', 'failed', 'skipped')
  ),
  constraint customer_followup_events_error_length_check check (error_code is null or length(error_code) <= 120)
);

create index if not exists customer_followup_events_customer_idx
on public.customer_followup_events (customer_id, created_at desc);

create table if not exists public.customer_followup_unsubscribe_tokens (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  constraint customer_followup_unsubscribe_tokens_hash_check check (token_hash ~ '^[a-f0-9]{64}$')
);

create index if not exists customer_followup_unsubscribe_tokens_customer_idx
on public.customer_followup_unsubscribe_tokens (customer_id, created_at desc);

create table if not exists public.customer_review_tokens (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  token_hash text not null unique,
  reminder_stage text,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  constraint customer_review_tokens_hash_check check (token_hash ~ '^[a-f0-9]{64}$'),
  constraint customer_review_tokens_stage_check check (
    reminder_stage is null
    or reminder_stage in ('two_month', 'six_month', 'twelve_month')
  )
);

create index if not exists customer_review_tokens_customer_idx
on public.customer_review_tokens (customer_id, created_at desc);

alter table public.customer_references
  add column if not exists customer_id bigint references public.customers(id) on delete set null;

alter table public.customer_references
  add column if not exists kontakt_email_normalized text;

alter table public.customer_references
  add column if not exists review_matched_at timestamptz;

alter table public.customer_references
  add column if not exists rating integer;

alter table public.customer_references
  add column if not exists public_consent boolean not null default true;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_references_rating_check'
  ) then
    alter table public.customer_references
      add constraint customer_references_rating_check
      check (rating is null or rating between 1 and 5);
  end if;
end $$;

create index if not exists customer_references_kontakt_email_normalized_idx
on public.customer_references (kontakt_email_normalized)
where kontakt_email_normalized is not null and kontakt_email_normalized <> '';

create index if not exists customer_references_customer_id_idx
on public.customer_references (customer_id)
where customer_id is not null;

create or replace function public.set_customers_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_customers_updated_at on public.customers;
create trigger set_customers_updated_at
before update on public.customers
for each row
execute function public.set_customers_updated_at();

create or replace function public.log_customer_followup_event(
  p_customer_id bigint,
  p_event_type text,
  p_reminder_stage text default null,
  p_status text default null,
  p_error_code text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.customer_followup_events (
    customer_id,
    event_type,
    reminder_stage,
    status,
    error_code,
    actor_user_id
  )
  values (
    p_customer_id,
    p_event_type,
    p_reminder_stage,
    p_status,
    nullif(left(coalesce(p_error_code, ''), 120), ''),
    auth.uid()
  );
end;
$$;

revoke all on function public.log_customer_followup_event(bigint, text, text, text, text) from public;
grant execute on function public.log_customer_followup_event(bigint, text, text, text, text) to service_role;

create or replace function public.audit_customer_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_type text;
begin
  if tg_op = 'INSERT' then
    perform public.log_customer_followup_event(new.id, 'customer_created');
    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.customer_followup_events (customer_id, event_type, actor_user_id)
    values (old.id, 'customer_deleted', auth.uid());
    return old;
  end if;

  v_event_type := case
    when old.follow_up_enabled is distinct from new.follow_up_enabled
      then case when new.follow_up_enabled then 'follow_up_enabled' else 'follow_up_disabled' end
    when old.follow_up_permission_status is distinct from new.follow_up_permission_status
      then 'permission_status_changed'
    when old.review_status is distinct from new.review_status
      then case when new.review_status = 'manual_confirmed' then 'review_manually_confirmed' else 'review_status_changed' end
    when old.follow_up_opt_out is distinct from new.follow_up_opt_out and new.follow_up_opt_out = true
      then 'customer_opted_out'
    else 'customer_updated'
  end;

  perform public.log_customer_followup_event(new.id, v_event_type);
  return new;
end;
$$;

drop trigger if exists audit_customer_change on public.customers;
create trigger audit_customer_change
after insert or update or delete on public.customers
for each row
execute function public.audit_customer_change();

create or replace function public.prepare_reference_customer_match()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id bigint;
begin
  new.kontakt_email_normalized := lower(btrim(coalesce(new.kontakt_email, '')));

  if new.kontakt_email_normalized = '' then
    new.customer_id := null;
    return new;
  end if;

  select c.id
  into v_customer_id
  from public.customers c
  where c.email_normalized = new.kontakt_email_normalized
    and c.deleted_at is null
  order by c.id asc
  limit 1;

  if v_customer_id is not null then
    new.customer_id := v_customer_id;
    new.review_matched_at := coalesce(new.review_matched_at, now());
  end if;

  return new;
end;
$$;

drop trigger if exists prepare_reference_customer_match on public.customer_references;
create trigger prepare_reference_customer_match
before insert or update of kontakt_email on public.customer_references
for each row
execute function public.prepare_reference_customer_match();

create or replace function public.apply_reference_customer_match()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.customer_id is null then
    return new;
  end if;

  update public.customers
  set
    review_status = case when review_status = 'manual_confirmed' then review_status else 'auto_matched' end,
    review_found_at = coalesce(review_found_at, now()),
    review_source = coalesce(review_source, 'asea_website'),
    matched_reference_id = new.id
  where id = new.customer_id
    and deleted_at is null
    and follow_up_opt_out = false;

  perform public.log_customer_followup_event(new.customer_id, 'review_auto_matched');
  return new;
end;
$$;

drop trigger if exists apply_reference_customer_match on public.customer_references;
create trigger apply_reference_customer_match
after insert or update of kontakt_email, customer_id on public.customer_references
for each row
execute function public.apply_reference_customer_match();

create or replace function public.rematch_customer_references_for_customer()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reference_id bigint;
begin
  if new.deleted_at is not null then
    return new;
  end if;

  update public.customer_references
  set kontakt_email_normalized = lower(btrim(coalesce(kontakt_email, '')))
  where kontakt_email is not null
    and coalesce(kontakt_email_normalized, '') <> lower(btrim(coalesce(kontakt_email, '')));

  update public.customer_references
  set customer_id = null
  where customer_id = new.id
    and coalesce(kontakt_email_normalized, '') <> new.email_normalized;

  update public.customer_references
  set
    customer_id = new.id,
    review_matched_at = coalesce(review_matched_at, now())
  where kontakt_email_normalized = new.email_normalized
    and coalesce(kontakt_email_normalized, '') <> ''
    and (customer_id is null or customer_id = new.id);

  select id
  into v_reference_id
  from public.customer_references
  where customer_id = new.id
  order by created_at desc, id desc
  limit 1;

  if v_reference_id is not null then
    update public.customers
    set
      review_status = case when review_status = 'manual_confirmed' then review_status else 'auto_matched' end,
      review_found_at = coalesce(review_found_at, now()),
      review_source = coalesce(review_source, 'asea_website'),
      matched_reference_id = coalesce(matched_reference_id, v_reference_id)
    where id = new.id
      and deleted_at is null
      and follow_up_opt_out = false;

    perform public.log_customer_followup_event(new.id, 'review_auto_matched');
  end if;

  return new;
end;
$$;

drop trigger if exists rematch_customer_references_for_customer on public.customers;
create trigger rematch_customer_references_for_customer
after insert or update of email on public.customers
for each row
execute function public.rematch_customer_references_for_customer();

alter table public.customers enable row level security;
alter table public.customer_followup_events enable row level security;
alter table public.customer_followup_unsubscribe_tokens enable row level security;
alter table public.customer_review_tokens enable row level security;

revoke all on table public.customers from anon, authenticated;
revoke all on table public.customer_followup_events from anon, authenticated;
revoke all on table public.customer_followup_unsubscribe_tokens from anon, authenticated;
revoke all on table public.customer_review_tokens from anon, authenticated;

grant select, insert, update, delete on table public.customers to authenticated;
grant select on table public.customer_followup_events to authenticated;

do $$
declare
  v_customer_sequence regclass;
  v_event_sequence regclass;
  v_token_sequence regclass;
  v_review_token_sequence regclass;
begin
  select pg_get_serial_sequence('public.customers', 'id')::regclass into v_customer_sequence;
  if v_customer_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', v_customer_sequence);
  end if;

  select pg_get_serial_sequence('public.customer_followup_events', 'id')::regclass into v_event_sequence;
  if v_event_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', v_event_sequence);
  end if;

  select pg_get_serial_sequence('public.customer_followup_unsubscribe_tokens', 'id')::regclass into v_token_sequence;
  if v_token_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', v_token_sequence);
  end if;

  select pg_get_serial_sequence('public.customer_review_tokens', 'id')::regclass into v_review_token_sequence;
  if v_review_token_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', v_review_token_sequence);
  end if;
end $$;

drop policy if exists "customers admin read" on public.customers;
create policy "customers admin read"
on public.customers
for select
to authenticated
using (public.is_admin());

drop policy if exists "customers admin insert" on public.customers;
create policy "customers admin insert"
on public.customers
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "customers admin update" on public.customers;
create policy "customers admin update"
on public.customers
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "customers admin delete" on public.customers;
create policy "customers admin delete"
on public.customers
for delete
to authenticated
using (public.is_admin());

drop policy if exists "customer followup events admin read" on public.customer_followup_events;
create policy "customer followup events admin read"
on public.customer_followup_events
for select
to authenticated
using (public.is_admin());

create or replace function public.unsubscribe_customer_followup(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token_hash text;
  v_customer_id bigint;
begin
  if p_token is null or length(p_token) < 32 then
    return true;
  end if;

  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  select customer_id
  into v_customer_id
  from public.customer_followup_unsubscribe_tokens
  where token_hash = v_token_hash
  limit 1;

  if v_customer_id is null then
    return true;
  end if;

  update public.customer_followup_unsubscribe_tokens
  set used_at = coalesce(used_at, now())
  where token_hash = v_token_hash;

  update public.customers
  set
    follow_up_opt_out = true,
    follow_up_opted_out_at = coalesce(follow_up_opted_out_at, now()),
    follow_up_enabled = false,
    follow_up_permission_status = 'revoked'
  where id = v_customer_id;

  perform public.log_customer_followup_event(v_customer_id, 'customer_opted_out');
  return true;
end;
$$;

revoke all on function public.unsubscribe_customer_followup(text) from public;
grant execute on function public.unsubscribe_customer_followup(text) to anon, authenticated;

create or replace function public.register_customer_unsubscribe_token(
  p_customer_id bigint,
  p_token_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_customer_id is null or p_token_hash !~ '^[a-f0-9]{64}$' then
    return false;
  end if;

  insert into public.customer_followup_unsubscribe_tokens (customer_id, token_hash)
  values (p_customer_id, p_token_hash)
  on conflict (token_hash) do nothing;

  return true;
end;
$$;

revoke all on function public.register_customer_unsubscribe_token(bigint, text) from public;
grant execute on function public.register_customer_unsubscribe_token(bigint, text) to service_role;

create or replace function public.register_customer_review_token(
  p_customer_id bigint,
  p_token_hash text,
  p_reminder_stage text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_customer_id is null
    or p_token_hash !~ '^[a-f0-9]{64}$'
    or (
      p_reminder_stage is not null
      and p_reminder_stage not in ('two_month', 'six_month', 'twelve_month')
    )
  then
    return false;
  end if;

  insert into public.customer_review_tokens (customer_id, token_hash, reminder_stage)
  values (p_customer_id, p_token_hash, p_reminder_stage)
  on conflict (token_hash) do nothing;

  return true;
end;
$$;

revoke all on function public.register_customer_review_token(bigint, text, text) from public;
grant execute on function public.register_customer_review_token(bigint, text, text) to service_role;

create or replace function public.submit_customer_review_with_token(
  p_token text,
  p_rating integer,
  p_beschreibung text,
  p_ort text default '',
  p_public_consent boolean default false
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token_hash text;
  v_token record;
  v_customer record;
  v_reference_id bigint;
  v_description text;
  v_location text;
  v_year integer;
begin
  if p_token is null or length(p_token) < 32 then
    return false;
  end if;

  if p_rating is null or p_rating < 1 or p_rating > 5 then
    return false;
  end if;

  v_description := left(btrim(coalesce(p_beschreibung, '')), 1600);
  v_location := left(btrim(coalesce(p_ort, '')), 120);

  if length(v_description) < 10 then
    return false;
  end if;

  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  select id, customer_id, reminder_stage, used_at
  into v_token
  from public.customer_review_tokens
  where token_hash = v_token_hash
  limit 1;

  if not found then
    return false;
  end if;

  if v_token.used_at is not null then
    return true;
  end if;

  update public.customer_review_tokens
  set used_at = now()
  where id = v_token.id
    and used_at is null;

  if not found then
    return true;
  end if;

  select
    id,
    name,
    email,
    email_normalized,
    purchased_item,
    purchase_date
  into v_customer
  from public.customers
  where id = v_token.customer_id
    and deleted_at is null
  limit 1;

  if not found then
    return false;
  end if;

  v_year := coalesce(
    extract(year from v_customer.purchase_date)::integer,
    extract(year from now())::integer
  );

  insert into public.customer_references (
    kundenname,
    ort,
    modell,
    jahr,
    beschreibung,
    bild_url,
    rating,
    public_consent,
    sichtbar,
    status,
    kontakt_email,
    kontakt_telefon,
    customer_id,
    kontakt_email_normalized,
    review_matched_at
  )
  values (
    left(coalesce(nullif(btrim(v_customer.name), ''), 'ASEA Kunde'), 160),
    v_location,
    left(coalesce(nullif(btrim(v_customer.purchased_item), ''), 'ASEA Anhänger'), 180),
    v_year,
    v_description,
    '',
    p_rating,
    coalesce(p_public_consent, false),
    false,
    'pending',
    v_customer.email,
    '',
    v_customer.id,
    v_customer.email_normalized,
    now()
  )
  returning id into v_reference_id;

  update public.customers
  set
    review_status = case when review_status = 'manual_confirmed' then review_status else 'auto_matched' end,
    review_found_at = coalesce(review_found_at, now()),
    review_source = coalesce(review_source, 'asea_website'),
    matched_reference_id = v_reference_id,
    follow_up_enabled = false,
    six_month_email_status = case
      when six_month_email_status in ('pending', 'failed', 'processing') then 'skipped'
      else six_month_email_status
    end,
    twelve_month_email_status = case
      when twelve_month_email_status in ('pending', 'failed', 'processing') then 'skipped'
      else twelve_month_email_status
    end
  where id = v_customer.id;

  perform public.log_customer_followup_event(
    v_customer.id,
    'review_submitted_via_token',
    v_token.reminder_stage,
    null,
    null
  );

  return true;
end;
$$;

revoke all on function public.submit_customer_review_with_token(text, integer, text, text, boolean) from public;
grant execute on function public.submit_customer_review_with_token(text, integer, text, text, boolean) to anon, authenticated;

create or replace function public.verify_customer_reminder_claim(
  p_customer_id bigint,
  p_stage text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.customers c
    where c.id = p_customer_id
      and c.deleted_at is null
      and c.follow_up_enabled = true
      and c.follow_up_opt_out = false
      and c.follow_up_permission_status in ('consented', 'existing_customer_permitted')
      and c.review_status = 'none'
      and c.review_found_at is null
      and c.manual_review_confirmed_at is null
      and not (c.twelve_month_email_status = 'sent' or c.twelve_month_email_sent_at is not null)
      and (
        (p_stage = 'two_month' and c.two_month_email_status = 'processing')
        or (p_stage = 'six_month' and c.six_month_email_status = 'processing')
        or (p_stage = 'twelve_month' and c.twelve_month_email_status = 'processing')
      )
  );
$$;

revoke all on function public.verify_customer_reminder_claim(bigint, text) from public;
grant execute on function public.verify_customer_reminder_claim(bigint, text) to service_role;

create or replace function public.claim_due_customer_reminders(p_limit integer default 20)
returns table (
  customer_id bigint,
  reminder_stage text,
  customer_name text,
  customer_email text,
  preferred_language text,
  purchased_item text,
  purchase_date date
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with due as (
    select
      c.id,
      case
        when c.two_month_email_status in ('pending', 'failed')
          and c.two_month_email_attempts < 3
          and (c.two_month_email_attempted_at is null or c.two_month_email_attempted_at < now() - interval '1 day')
          and (c.purchase_date + interval '2 months')::date <= (now() at time zone 'Europe/Vienna')::date
          then 'two_month'
        when c.six_month_email_status in ('pending', 'failed')
          and c.six_month_email_attempts < 3
          and (c.six_month_email_attempted_at is null or c.six_month_email_attempted_at < now() - interval '1 day')
          and (c.purchase_date + interval '6 months')::date <= (now() at time zone 'Europe/Vienna')::date
          then 'six_month'
        when c.twelve_month_email_status in ('pending', 'failed')
          and c.twelve_month_email_attempts < 3
          and (c.twelve_month_email_attempted_at is null or c.twelve_month_email_attempted_at < now() - interval '1 day')
          and (c.purchase_date + interval '12 months')::date <= (now() at time zone 'Europe/Vienna')::date
          then 'twelve_month'
        else null
      end as stage
    from public.customers c
    where c.deleted_at is null
      and c.follow_up_enabled = true
      and c.follow_up_opt_out = false
      and c.follow_up_permission_status in ('consented', 'existing_customer_permitted')
      and c.review_status = 'none'
      and c.review_found_at is null
      and c.manual_review_confirmed_at is null
      and not (c.twelve_month_email_status = 'sent' or c.twelve_month_email_sent_at is not null)
    order by c.purchase_date asc, c.id asc
    limit least(greatest(coalesce(p_limit, 20), 1), 50)
    for update skip locked
  ),
  selected_due as (
    select due.id, due.stage
    from due
    where due.stage is not null
  ),
  updated as (
    update public.customers c
    set
      two_month_email_status = case when selected_due.stage = 'two_month' then 'processing' else c.two_month_email_status end,
      two_month_email_attempted_at = case when selected_due.stage = 'two_month' then now() else c.two_month_email_attempted_at end,
      two_month_email_attempts = case when selected_due.stage = 'two_month' then c.two_month_email_attempts + 1 else c.two_month_email_attempts end,
      six_month_email_status = case when selected_due.stage = 'six_month' then 'processing' else c.six_month_email_status end,
      six_month_email_attempted_at = case when selected_due.stage = 'six_month' then now() else c.six_month_email_attempted_at end,
      six_month_email_attempts = case when selected_due.stage = 'six_month' then c.six_month_email_attempts + 1 else c.six_month_email_attempts end,
      twelve_month_email_status = case when selected_due.stage = 'twelve_month' then 'processing' else c.twelve_month_email_status end,
      twelve_month_email_attempted_at = case when selected_due.stage = 'twelve_month' then now() else c.twelve_month_email_attempted_at end,
      twelve_month_email_attempts = case when selected_due.stage = 'twelve_month' then c.twelve_month_email_attempts + 1 else c.twelve_month_email_attempts end
    from selected_due
    where c.id = selected_due.id
    returning
      c.id,
      selected_due.stage,
      c.name,
      c.email,
      c.preferred_language,
      c.purchased_item,
      c.purchase_date
  )
  select
    updated.id,
    updated.stage,
    updated.name,
    updated.email,
    updated.preferred_language,
    updated.purchased_item,
    updated.purchase_date
  from updated;
end;
$$;

revoke all on function public.claim_due_customer_reminders(integer) from public;
grant execute on function public.claim_due_customer_reminders(integer) to service_role;

create or replace function public.record_customer_reminder_result(
  p_customer_id bigint,
  p_stage text,
  p_status text,
  p_error_code text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('sent', 'failed', 'skipped') then
    return false;
  end if;

  if p_stage = 'two_month' then
    update public.customers
    set
      two_month_email_status = p_status,
      two_month_email_sent_at = case when p_status = 'sent' then now() else two_month_email_sent_at end
    where id = p_customer_id;
  elsif p_stage = 'six_month' then
    update public.customers
    set
      six_month_email_status = p_status,
      six_month_email_sent_at = case when p_status = 'sent' then now() else six_month_email_sent_at end
    where id = p_customer_id;
  elsif p_stage = 'twelve_month' then
    update public.customers
    set
      twelve_month_email_status = p_status,
      twelve_month_email_sent_at = case when p_status = 'sent' then now() else twelve_month_email_sent_at end
    where id = p_customer_id;
  else
    return false;
  end if;

  perform public.log_customer_followup_event(
    p_customer_id,
    'reminder_' || p_status,
    p_stage,
    p_status,
    p_error_code
  );

  return true;
end;
$$;

revoke all on function public.record_customer_reminder_result(bigint, text, text, text) from public;
grant execute on function public.record_customer_reminder_result(bigint, text, text, text) to service_role;

drop policy if exists "customer references public visible read" on public.customer_references;
create policy "customer references public visible read"
on public.customer_references
for select
to anon
using (status = 'approved' and sichtbar = true and public_consent = true);

create or replace view public.customer_references_public as
select
  id,
  kundenname,
  ort,
  modell,
  jahr,
  beschreibung,
  bild_url,
  sichtbar,
  status,
  created_at,
  rating
from public.customer_references
where status = 'approved'
  and sichtbar = true
  and public_consent = true;

grant select on public.customer_references_public to anon, authenticated;

-- Sicherheitsziel:
-- anon: kein Zugriff auf customers, events oder Token-Hashes.
-- normale authenticated User: kein Zugriff ohne public.is_admin().
-- Admins: nur ueber RLS gesicherte Verwaltung.
-- Cron/API: nur serverseitig mit service_role fuer die Reminder-RPCs.
