-- Fuehre diese Datei komplett im Supabase SQL Editor aus.
-- Admin-E-Mail: bastianhochreither@gmx.at

create table if not exists public.customer_references (
  id bigint generated by default as identity primary key,
  kundenname text not null default '',
  ort text not null default '',
  modell text not null default 'Verkaufsanhänger',
  jahr integer not null default extract(year from now())::integer,
  beschreibung text not null default '',
  bild_url text not null default '',
  sichtbar boolean not null default true,
  status text not null default 'approved',
  kontakt_email text not null default '',
  kontakt_telefon text not null default '',
  created_at timestamptz not null default now()
);

alter table public.customer_references add column if not exists status text not null default 'approved';
alter table public.customer_references add column if not exists kontakt_email text not null default '';
alter table public.customer_references add column if not exists kontakt_telefon text not null default '';
alter table public.customer_references add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_references_status_check'
  ) then
    alter table public.customer_references
      add constraint customer_references_status_check
      check (status in ('approved', 'pending', 'rejected'));
  end if;
end $$;

alter table public.customer_references enable row level security;

grant select on table public.customer_references to anon, authenticated;
grant insert on table public.customer_references to anon, authenticated;
grant update, delete on table public.customer_references to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce((auth.jwt() ->> 'email') = 'bastianhochreither@gmx.at', false);
$$;

drop policy if exists "customer references public visible read" on public.customer_references;
create policy "customer references public visible read"
on public.customer_references
for select
to anon, authenticated
using ((status = 'approved' and sichtbar = true) or public.is_admin());

drop policy if exists "customer references public pending insert" on public.customer_references;
create policy "customer references public pending insert"
on public.customer_references
for insert
to anon, authenticated
with check (status = 'pending' and sichtbar = false);

drop policy if exists "customer references admin insert" on public.customer_references;
create policy "customer references admin insert"
on public.customer_references
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "customer references admin update" on public.customer_references;
create policy "customer references admin update"
on public.customer_references
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "customer references admin delete" on public.customer_references;
create policy "customer references admin delete"
on public.customer_references
for delete
to authenticated
using (public.is_admin());

insert into public.customer_references (id, kundenname, ort, modell, jahr, beschreibung, bild_url, sichtbar, status, kontakt_email, kontakt_telefon)
values
  (1, 'Würstelstand Huber', 'Wien', 'Verkaufsanhänger', 2023, 'Mobiler Würstelstand im Wiener Prater - täglich im Einsatz.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-85.jpg', true, 'approved', '', ''),
  (2, 'Café Moser', 'Salzburg', 'Messe- und Präsentationsanhänger', 2022, 'Café-Präsentationen bei Events und Stadtfesten in Salzburg.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-4-2.jpg', true, 'approved', '', ''),
  (3, 'Getränke Steinbauer', 'Linz', 'Kühlanhänger', 2024, 'Frischlieferungen von Getränken an Gastronomiebetriebe im Großraum Linz.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-2-1.jpg', true, 'approved', '', ''),
  (4, 'Imbiss Kowalski', 'Graz', 'Verkaufsanhänger', 2023, 'Schnellimbiss am Hauptplatz Graz - beliebt bei Marktbesuchern.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-10.jpg', true, 'approved', '', ''),
  (5, 'Bäckerei Pichler', 'Wels', 'Verkaufsanhänger', 2022, 'Frische Backwaren direkt vom Anhänger auf dem Wochenmarkt.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-86.jpg', false, 'approved', '', ''),
  (6, 'Eventservice Huemer', 'Innsbruck', 'Messe- und Präsentationsanhänger', 2024, 'Professionelle Event-Bewirtung bei Tiroler Outdoor-Veranstaltungen.', 'https://www.verkaufsanhaenger-asea.at/wp/wp-content/uploads/Verkaufsanhaenger-Asea-aus-Waldburg-in-Oberoesterreich-5.jpg', true, 'approved', '', '')
on conflict (id) do update set
  kundenname = excluded.kundenname,
  ort = excluded.ort,
  modell = excluded.modell,
  jahr = excluded.jahr,
  beschreibung = excluded.beschreibung,
  bild_url = excluded.bild_url,
  sichtbar = excluded.sichtbar,
  status = excluded.status,
  kontakt_email = excluded.kontakt_email,
  kontakt_telefon = excluded.kontakt_telefon;

select setval(
  pg_get_serial_sequence('public.customer_references', 'id'),
  coalesce((select max(id) from public.customer_references), 1)
);
