-- Fuehre diese Datei komplett im Supabase SQL Editor aus.

create table if not exists public.customer_references (
  id bigint generated by default as identity primary key,
  kundenname text not null default '',
  ort text not null default '',
  modell text not null default 'Verkaufsanhänger',
  jahr integer not null default extract(year from now())::integer,
  beschreibung text not null default '',
  bild_url text not null default '',
  sichtbar boolean not null default true,
  status text not null default 'approved',
  kontakt_email text not null default '',
  kontakt_telefon text not null default '',
  created_at timestamptz not null default now()
);

alter table public.customer_references add column if not exists status text not null default 'approved';
alter table public.customer_references add column if not exists kontakt_email text not null default '';
alter table public.customer_references add column if not exists kontakt_telefon text not null default '';
alter table public.customer_references add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_references_status_check'
  ) then
    alter table public.customer_references
      add constraint customer_references_status_check
      check (status in ('approved', 'pending', 'rejected'));
  end if;
end $$;

alter table public.customer_references enable row level security;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;
grant select on table public.admin_users to authenticated;

revoke select on table public.customer_references from anon, authenticated;
revoke insert on table public.customer_references from anon, authenticated;
grant insert (
  kundenname,
  ort,
  modell,
  jahr,
  beschreibung,
  bild_url,
  sichtbar,
  status,
  kontakt_email,
  kontakt_telefon
) on table public.customer_references to anon, authenticated;
grant select (
  id,
  kundenname,
  ort,
  modell,
  jahr,
  beschreibung,
  bild_url,
  sichtbar,
  status,
  created_at
) on table public.customer_references to anon;
grant select on table public.customer_references to authenticated;
grant update, delete on table public.customer_references to authenticated;
revoke usage, select on all sequences in schema public from anon, authenticated;
do $$
declare
  v_reference_sequence regclass;
begin
  select pg_get_serial_sequence('public.customer_references', 'id')::regclass
  into v_reference_sequence;

  if v_reference_sequence is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', v_reference_sequence);
  end if;
end $$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
      and active = true
      and role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "admin users admin read" on public.admin_users;
create policy "admin users admin read"
on public.admin_users
for select
to authenticated
using (public.is_admin());

drop policy if exists "customer references public visible read" on public.customer_references;
create policy "customer references public visible read"
on public.customer_references
for select
to anon
using (status = 'approved' and sichtbar = true);

drop policy if exists "customer references admin read" on public.customer_references;
create policy "customer references admin read"
on public.customer_references
for select
to authenticated
using (public.is_admin());

drop policy if exists "customer references public pending insert" on public.customer_references;
create policy "customer references public pending insert"
on public.customer_references
for insert
to anon, authenticated
with check (status = 'pending' and sichtbar = false);

drop policy if exists "customer references admin insert" on public.customer_references;
create policy "customer references admin insert"
on public.customer_references
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "customer references admin update" on public.customer_references;
create policy "customer references admin update"
on public.customer_references
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "customer references admin delete" on public.customer_references;
create policy "customer references admin delete"
on public.customer_references
for delete
to authenticated
using (public.is_admin());

create or replace view public.customer_references_public as
select
  id,
  kundenname,
  ort,
  modell,
  jahr,
  beschreibung,
  bild_url,
  sichtbar,
  status,
  created_at
from public.customer_references
where status = 'approved'
  and sichtbar = true;

grant select on public.customer_references_public to anon, authenticated;

-- Keine Demo-Referenzen automatisch anlegen.
-- Veröffentliche nur echte Referenzen, für die die nötigen Rechte und Freigaben vorliegen.
--
-- Erstes Admin-Konto freigeben:
-- 1. Lege den Admin-Benutzer in Supabase unter Authentication > Users an.
-- 2. Fuehre danach einmal aus:
--
-- insert into public.admin_users (user_id, email, role, active)
-- select id, email, 'owner', true
-- from auth.users
-- where email = 'deine-admin-mail@example.com'
-- on conflict (user_id) do update set
--   email = excluded.email,
--   role = excluded.role,
--   active = true,
--   updated_at = now();
